version: '4.30'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES:DB: ${SPRING_DATASOURCE_DB}
    ports:
      - "5342:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data